name: Deploy to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }} # 인스턴스 IP
          username: ${{ secrets.USER_NAME }} # 우분투 아이디
          key: ${{ secrets.KEY }} # ec2 instance pem key
          port: ${{ secrets.PORT }} # 접속포트
          script: | # 실행할 스크립트
            cd /home/ubuntu/Server || exit 1
            git pull origin main
            npm install --force
            pm2 kill || true
            pm2 start src/server.js
