name: Deploy to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }} # 인스턴스 IP
          username: ${{ secrets.USER_NAME }} # 우분투 아이디
          key: ${{ secrets.KEY }} # ec2 instance pem key
          port: ${{ secrets.PORT }} # 접속포트
          script: | # 실행할 스크립트
            cd /home/ubuntu/Server
            git pull origin main
            npm install --force
            pm2 kill
            pm2 start src/server.js

      # 성공 알림: 배포가 성공했을 경우에만 실행
      - name: Send Discord Success Notification
        if: success() # 이전 단계가 성공했을 경우에만 실행
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
               -d '{"content": "✅ 배포 완료: AWS EC2로의 배포가 성공적으로 완료되었습니다."}' \
               $DISCORD_WEBHOOK_URL

      # 실패 알림: 배포가 실패했을 경우에만 실행
      - name: Send Discord Failure Notification
        if: failure() # 이전 단계가 실패했을 경우에만 실행
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
               -d '{"content": "❌ 배포 실패: AWS EC2로의 배포가 실패했습니다."}' \
               $DISCORD_WEBHOOK_URL
